dist: xenial

services:
  - docker

language: python

python: 3.8

before_install:
  - docker-compose -v
  - docker -v

matrix:
  include:
    - name: Test results
      script: tox -e py38
    - name: Black template
      script: tox -e black-template
    - name: Bare metal
      script: sh tests/test_bare.sh
      services:
        - postgresql
        - redis-server

install:
  - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always
